### ISSUE TITLE
I don't know this is bug or not

### ISSUE THREAD

**Issue by afrizaloky** [open-wa/wa-automate-nodejs#1380]
**Describe the bug**

i use openwa 3.6.3
i try using sendText with null paramater, sendText(from, null). The function after this sendText can't executed. 
for example:
client.sendText(from, '') => this empty string parameter doesn't make bug
client.sendText(from, 'test') => this message can be send
client.sendText(from, null) => this message can't be send and the code stop in there
client.sendText(from, 'test2') => not executed
client.sendText(from, asq) => not executed
client.sendText(from, 'test3') => not executed

for another example:
client.sendText(from, '') => this empty parameter doesn't make bug
client.sendText(from, 'test') => this message can be send
client.sendText(from, 'test2') => this message can be send
client.sendText(from, asq) => note: asq is undefined variable. this message can't be send and the code stop in there
client.sendText(from, 'test3') => not executed

i don't know this is bug or not, but it is annoying for me.  sorry for bad documentation

**Comment by smashah** [comment]
@afrizaloky are you using typescript?

**Comment by afrizaloky** [comment]
i use nodejs

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.4](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.3...3.6.4) (2021-02-23)

- Release 3.6.4 [`a0d9303`](https://github.com/open-wa/wa-automate-nodejs/commit/a0d9303b5ab53bf5334aeea9f7619eccaa6da174)
- 📝  chat IDs now show up correctly in intellisense [`793f428`](https://github.com/open-wa/wa-automate-nodejs/commit/793f428475187155fd548dc7dff275de3c67c86c)
- ⚡️ Improved package size and postman generation performance [`7db0064`](https://github.com/open-wa/wa-automate-nodejs/commit/7db006409e2e3faa0beec722e28ae69187f19986)
- ✨ [NEW] `isChatMuted` - check if chat is muted [`d98df11`](https://github.com/open-wa/wa-automate-nodejs/commit/d98df1183fc1cb9053050a38f8622c290ef5b749)
- 💚  emojis fixed in release image changelog [`1444a6b`](https://github.com/open-wa/wa-automate-nodejs/commit/1444a6be606d341287a032f205133a3a2b5d1a2a)
- 🚸 sticker server requests hard limit of 1.5mb and throws error #1370 [`3f3906f`](https://github.com/open-wa/wa-automate-nodejs/commit/3f3906fc63236763dacf7c8679c2d10e2cc7eb32)
- 🐛  `hideTags` parameter now optional [`6cba478`](https://github.com/open-wa/wa-automate-nodejs/commit/6cba478fd9451a0fb3f7673db36b7ba17e2604da)
- 📝  intellisense should now pick up documentation [`920f5a1`](https://github.com/open-wa/wa-automate-nodejs/commit/920f5a1d745afaead39b381cb1a85459d9008c3e)
- 🩹  `sendText` should no longer allow `null` or `undefined` #1380 [`26e2bb7`](https://github.com/open-wa/wa-automate-nodejs/commit/26e2bb764fec48243002cab81680199055d8c026)

**Comment by smashah** [comment]
@afrizaloky can you update to the latest version and try to send a text with null or undefined again and see if it gets stuck

**Comment by afrizaloky** [comment]
when null is not stuck, but when undefined variable still get stuck

**Comment by afrizaloky** [comment]
closed. thank you
