### ISSUE TITLE
Not all Giphy link can be sendGiphyAsSticker

### ISSUE THREAD

**Issue by responsablyat** [open-wa/wa-automate-nodejs#799]
**Describe the bug**
I am using the sendGiphyAsSticker, but not all the link are able to send as a sticker
I have two link of giphy, this link cannot send as a sticker :
https://media.giphy.com/media/JmUOyXVQufiSODqj2f/source.gif
but this link is possible  :
https://media.giphy.com/media/h8m2STe9JssHRCwM2l/source.gif
![image](https://user-images.githubusercontent.com/25841530/92672645-530de780-f343-11ea-939c-59b9094045de.png)

**Steps to Reproduce**
1. Send the first link to my bot, and he will send me the sticker
2. Send the second link to my bot, and he will send nothing, and no error printed on the console
3. The bot doesn't seem to be stuck because he can reply any other command I give

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**
the bot should send the sticker on both giphy url given.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION:  '2.2037.5' ,
  PAGE_UA: 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36',
  WA_AUTOMATE_VERSION:  '2.0.18'   ,
  BROWSER_VERSION: 'HeadlessChrome/84.0.4147.89'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
![image](https://user-images.githubusercontent.com/25841530/92672779-b0099d80-f343-11ea-9e61-520b337955bc.png)

**Host (please complete the following information):**
 - OS: Android

**Additional context**
i tried to catch the error but there is no error printed on console

**Comment by smashah** [comment]
I tested both links and both are working correctly. Are you uploading these gifs yourself to GIPHY?

**Comment by responsablyat** [comment]
> I tested both links and both are working correctly. Are you uploading these gifs yourself to GIPHY?

Yeah i upload it with the giphy api, so if i send a video to my bot, he will convert it to gif than he will upload it to giphy

**Comment by responsablyat** [comment]
> I tested both links and both are working correctly. Are you uploading these gifs yourself to GIPHY?

this is how my bot works,
the user will send video
than my bot will convert it to gif
after that my bot will upload the gif to giphy using the giphy API
https://streamable.com/ikykyo

**Comment by smashah** [comment]
@responsablyat please provide the api response from giphy

**Comment by kevin4dhd** [comment]
{
    data: { id: 'kGQSUeK28A91OJekNO' },
    meta: { msg: 'OK', status: 200 }
}

my body

**Comment by kevin4dhd** [comment]
MY CODE

`if (message.mimetype === 'video/mp4' && message.duration < 30) {
                let mensaje = message.caption.trim().toLowerCase();
                if (mensaje === "st" || mensaje === "/st") {
                    let tokenGiphy = 'TOKEN-XXXX';
                    const mediaData = await decryptMedia(message);
                    fs.writeFile(filename, mediaData, function (err) {
                        if (err) {
                            return console.log(err);
                        }
                        var options = {
                            url: 'https://upload.giphy.com/v1/gifs',
                            formData: {
                                api_key: tokenGiphy,
                                file: {
                                    value: fs.createReadStream(filename),
                                    options: {
                                        filename: filename,
                                        contentType: message.mimetype
                                    }
                                }
                            },
                            json: true
                        };
                        request.post(options, function (e, resp, body) {
                            console.log(body);
                            if (e || resp.statusCode !== 200) {
                                console.log('giphy upload failed: ' + e);
                                client.sendText(message.from, 'No se pudo crear el sticker animado, intentalo mañana...');
                            }
                            let url = 'https://media.giphy.com/media/' + body.data.id + '/source.gif';
                            console.log("Enviando...", url);
                            client.sendGiphyAsSticker(
                                message.chat.id,
                                url
                            ).then(res => {
                                console.log(res);
                            });
                        });
                    });
                }
            }`

**Comment by kevin4dhd** [comment]
MY CODE
![image](https://user-images.githubusercontent.com/22886367/92926749-210f8a80-f402-11ea-90f5-13392f33faa1.png)

**Comment by responsablyat** [comment]
> MY CODE
> ![image](https://user-images.githubusercontent.com/22886367/92926749-210f8a80-f402-11ea-90f5-13392f33faa1.png)

Are you getting the same error with this code?

**Comment by kevin4dhd** [comment]
@responsablyat No, it is an error that when uploading a video it converts it to .mov and not .gif and then sendGiphyAsSticker cannot process it

**Comment by responsablyat** [comment]
> @responsablyat please provide the api response from giphy

{
  data: { id: 'kHr2LAupgUuogCd19i' },
  meta: { msg: 'OK', status: 200 }
}

**Comment by responsablyat** [comment]
> @responsablyat No, it is an error that when uploading a video it converts it to .mov and not .gif and then sendGiphyAsSticker cannot process it

maybe you can use "gify" (https://www.npmjs.com/package/gify) to convert the video to gifs first then upload it to github

**Comment by kevin4dhd** [comment]
> > @responsablyat No, it is an error that when uploading a video it converts it to .mov and not .gif and then sendGiphyAsSticker cannot process it
> 
> maybe you can use "gify" (https://www.npmjs.com/package/gify) to convert the video to gifs first then upload it to github

Thank you

**Comment by kevin4dhd** [comment]
Now I got to the same error as you, I can't send an animated gif even though the "source.gif" already exists

![image](https://user-images.githubusercontent.com/22886367/92977533-e3871d80-f452-11ea-8632-83a96a91f247.png)


https://media.giphy.com/media/chiU6QPz6Dhn9eJ0td/source.gif

**Comment by responsablyat** [comment]
> Now I got to the same error as you, I can't send an animated gif even though the "source.gif" already exists
> 
> ![image](https://user-images.githubusercontent.com/22886367/92977533-e3871d80-f452-11ea-8632-83a96a91f247.png)
> 
> https://media.giphy.com/media/chiU6QPz6Dhn9eJ0td/source.gif

Yeah sometimes the sendGiphyAsSticker 
Working well, but sometime it doesnt, 
I have tried to lower the quality for lower size but it stays the same

**Comment by smashah** [comment]
it's not an issue of mov.

**Comment by responsablyat** [comment]
> it's not an issue of mov.

any idea why some link doesn't work sometimes?

**Comment by smashah** [comment]
@responsablyat @kevin4dhd 

I've implemented a fix via a patch. Should be live in about 5 mins.

you can now send the giphy id as the second param.

e.g:

```javascript
	await client.sendGiphyAsSticker(message.from, 'chiU6QPz6Dhn9eJ0td')
```

Please report back if it works.

**Comment by responsablyat** [comment]
![image](https://user-images.githubusercontent.com/25841530/92990573-b6487700-f507-11ea-889c-a146aab4065b.png)
![image](https://user-images.githubusercontent.com/25841530/92990578-ba749480-f507-11ea-9a2e-d7db8cd736ac.png)

i tried that but it still doesn't work, I have wait for 1-2 minutes but it still doesn't work with the same id above.

**Comment by kevin4dhd** [comment]
![image](https://user-images.githubusercontent.com/22886367/92990623-81a2d400-f4a3-11ea-87a4-164c91de2e0b.png)

for me it already works, but now this appears

**Comment by kevin4dhd** [comment]
The URL is this:
https://media.giphy.com/media/Kc1w5g4eoLeKPXzjAp/source.gif

The id is this:
Kc1w5g4eoLeKPXzjAp

send the animated sticker but now it appears "this content is not available"

My code:
![image](https://user-images.githubusercontent.com/22886367/92990730-4fde3d00-f4a4-11ea-9879-a5a9568830d5.png)

**Comment by responsablyat** [comment]
while i tried with a user-sent video, I got the same thing with Kevin, 
![image](https://user-images.githubusercontent.com/25841530/92990712-c57bf480-f508-11ea-8ee3-7154c19fdc6a.png)

this is my code
![image](https://user-images.githubusercontent.com/25841530/92990763-328f8a00-f509-11ea-941e-a8dbaecee409.png)


and I tried fixed id same as above, 
`	await client.sendGiphyAsSticker(message.from, 'chiU6QPz6Dhn9eJ0td')`
it send nothing

**Comment by kevin4dhd** [comment]
This has always happened, when I send an animated sticker it looks like this. What am I doing wrong?

![3b327474-3a7f-4696-8244-c985c169d33c](https://user-images.githubusercontent.com/22886367/92990996-2b836000-f4a6-11ea-9d59-4334f77c1fc0.jpg)

**Comment by responsablyat** [comment]
> This has always happened, when I send an animated sticker it looks like this. What am I doing wrong?
> 
> ![3b327474-3a7f-4696-8244-c985c169d33c](https://user-images.githubusercontent.com/22886367/92990996-2b836000-f4a6-11ea-9d59-4334f77c1fc0.jpg)
> 
> PS: On computer it looks good, on cell phone it looks distorted

same here, it also happens to me

**Comment by smashah** [comment]
There may be some processing time issue that you guys are dealing with. I would suggest waiting for a few minutes then send the sticker.

**Comment by responsablyat** [comment]
> There may be some processing time issue that you guys are dealing with. I would suggest waiting for a few minutes then send the sticker.

i tried this thing and it works I add 
`setTimeout(function(){client.sendGiphyAsSticker(message.from, url.split('/')[4])},60000)` 
and it work as I expected
I still tried to find the fastest time,

**Comment by smashah** [comment]
Yeah makes sense. It takes time for GIPHY to get around to processing your gif. It's never going to be a constant time. I'll make sure the method returns a "GIF_NOT_FOUND" or something if it detects a 404. What do you think? Then you can implement an exponential backoff at your end. @responsablyat @kevin4dhd

**Comment by kevin4dhd** [comment]
I would like it to work like this, it is the first idea that occurred to me, if it could be optimized it would be great, but I would like it not to send the sticker when it does not exist with a boolean variable so then you can place an interval

`const noSendWhenError = true;
                                const timeOut = 5 * 60 * 1000;
                                const tryAgain = 10 * 1000;
                                const timeTryNow = 0;
                                const interval = setInterval(async function()=>{
                                    let res = await client.sendGiphyAsSticker(message.from,body.data.id,noSendWhenError);
                                    timeTryNow += tryAgain;
                                    if(res !== 'GIF_NOT_FOUND'){
                                        //Send success
                                        clearInterval(interval);
                                    }else if(timeTryNow>timeOut){
                                        client.sendText(message.from,'Error: TIMEOUT');
                                        clearInterval(interval);
                                    } 
                                }, tryAgain);`

![image](https://user-images.githubusercontent.com/22886367/92995153-76ad6b00-f4c6-11ea-8b3b-36f587b75bdd.png)

**Comment by responsablyat** [comment]
@smashah @kevin4dhd thank you for help and issue fix, :D

**Comment by smashah** [comment]
or use an existing exponential backoff library:

https://www.npmjs.com/package/exponential-backoff

```javascript
import { backOff } from "exponential-backoff";


	const sendAnimatedSticker = async (to, id) => {
						const res = await client.sendGiphyAsSticker(to,id);
						return res==='GIF_NOT_FOUND' ? false : res;
						}

    const response = await backOff(() => sendAnimatedSticker(message.body, body.data.id));

```

**Comment by kevin4dhd** [comment]
> or use an existing exponential backoff library:
> 
> https://www.npmjs.com/package/exponential-backoff
> 
> ```js
> import { backOff } from "exponential-backoff";
> 
> 
> 	const sendAnimatedSticker = async (to, id) => {
> 						const res = await client.sendGiphyAsSticker(to,id);
> 						console.log(res);
> 						return res.startsWith('true') ? res : false;
> 						}
> 
>     const response = await backOff(() => sendAnimatedSticker(message.body, body.data.id));
> ```
> 
> This way I don't even have to make the change stated above.

perfect, i like that code
Today will you upload the update that does not send the gif if it is 404? or is it already available?

**Comment by kevin4dhd** [comment]
> @smashah @kevin4dhd thank you for help and issue fix, :D

One last question, did you manage to make your gifs less than 1MB? when I send it as a video it weighs 300kb, when I send it as a gif it weighs 2MB

**Comment by responsablyat** [comment]
> > @smashah @kevin4dhd thank you for help and issue fix, :D
> 
> One last question, did you manage to make your gifs less than 1MB? when I send it as a video it weighs 300kb, when I send it as a gif it weighs 2MB

![image](https://user-images.githubusercontent.com/25841530/92996494-42719300-f536-11ea-85d2-aeb2413d2fa8.png)
I am using this library https://www.npmjs.com/package/gify to convert video to lower gif size, 
(I am not so experienced at code so my code seems awkward)

**Comment by responsablyat** [comment]
> or use an existing exponential backoff library:
> 
> https://www.npmjs.com/package/exponential-backoff
> 
> ```js
> import { backOff } from "exponential-backoff";
> 
> 
> 	const sendAnimatedSticker = async (to, id) => {
> 						const res = await client.sendGiphyAsSticker(to,id);
> 						console.log(res);
> 						return res.startsWith('true') ? res : false;
> 						}
> 
>     const response = await backOff(() => sendAnimatedSticker(message.body, body.data.id));
> ```
> 
> This way I don't even have to make the change stated above.

@smashah 
so we don't need to convert the video to gif ? 
just upload the video to giphy, that's all?

**Comment by responsablyat** [comment]
> it's not an issue of mov.

@smashah 
so we don't need to convert the video to gif, we just need to upload the video directly to giphy?

**Comment by smashah** [comment]
Actually. The whole reason why the code completes and doesn't log an error is because giphy provides a placeholder for GIFs that haven't been processed yet to the right format. This problem may be tougher to fix than I previously thought. We need to find a way to check if the gif has been pricey by getting some sort of error code.

**Comment by responsablyat** [comment]
@smashah Thank You :D

**Comment by smashah** [comment]
@responsablyat @kevin4dhd I manually uploaded a large video to Giphy via the website and immediately tried to get the correct format in another page. Every time I tried to request it, it returned an HTML doc. So I use that as an indicator that the gif isn't processed. When this happens it will now return `GIF_NOT_FOUND` as a string. Eventually, it did return the correct file in the correct format.

Let me know if this works for you. For now, I think this is the best we can do.

**Comment by kevin4dhd** [comment]
> > > @smashah @kevin4dhd thank you for help and issue fix, :D
> > 
> > 
> > One last question, did you manage to make your gifs less than 1MB? when I send it as a video it weighs 300kb, when I send it as a gif it weighs 2MB
> 
> ![image](https://user-images.githubusercontent.com/25841530/92996530-8b294c00-f536-11ea-9265-45abe4f37941.png)
> 
> I am using this library https://www.npmjs.com/package/gify to convert video to lower gif size,
> (I am not so experienced at code so my code seems awkward)
> 
> also u don't need to convert the gif anymore, cause I tried to directly upload it as a video and it is works

I found a way to download 3M in a gif at 500kb

download the gify source code and change this line:
  var tmp = dir + '/%04d.png';
to this line
  var tmp = dir + '/%04d.jpg';

and this line
cmd.push ('/ tmp /' + id + '/*.png');
to this line
cmd.push ('/ tmp /' + id + '/*.jpg');

I have seen that if the gif weighs more than 2.5M the sendImageAsSticker method does not work

**Comment by responsablyat** [comment]
> > > > @smashah @kevin4dhd thank you for help and issue fix, :D
> > > 
> > > 
> > > One last question, did you manage to make your gifs less than 1MB? when I send it as a video it weighs 300kb, when I send it as a gif it weighs 2MB
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25841530/92996530-8b294c00-f536-11ea-9265-45abe4f37941.png)
> > I am using this library https://www.npmjs.com/package/gify to convert video to lower gif size,
> > (I am not so experienced at code so my code seems awkward)
> > also u don't need to convert the gif anymore, cause I tried to directly upload it as a video and it is works
> 
> I found a way to download 3M in a gif at 500kb
> 
> download the gify source code and change this line:
> var tmp = dir + '/%04d.png';
> to this line
> var tmp = dir + '/%04d.jpg';
> 
> and this line
> cmd.push ('/ tmp /' + id + '/_.png'); to this line cmd.push ('/ tmp /' + id + '/_.jpg');
> 
> I have seen that if the gif weighs more than 2.5M the sendImageAsSticker method does not work

thank you
